export type CasteEntry = { name: string; category: string; nigama: string };

export const CASTES: readonly CasteEntry[] = [
  { name: "Kumbar - ಕುಂಬಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Chakrasali - ಚಕ್ರಸಾಲಿ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Gunga - ಗುಣಗ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Ganagi - ಗಣಗಿ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Koyava - ಕೊಯವ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kula - ಕುಲ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kulaala - ಕುಲಾಲ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kumbaar - ಕುಂಬಾರ್", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "kumbaarda - ಕುಂಬಾರ್ಡ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kummaara - ಕುಮ್ಮಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kusavan - ಕುಸವನ್", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Maulya - ಮೂಲ್ಯ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Sajjana Kumbaara - ಸಜ್ಜನ ಕುಂಬಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Khumaara - ಖುಮಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kumbhara - ಕುಂಭಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Khumbhaara - ಖುಂಭಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kulaalar - ಕುಲಾಲರ್", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kaapu - ಕಾಪು", category: "3A", nigama: "Vokkaliga" },
  { name: "Balija - ಬಲಿಜ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Balajiga/Banajiga/Gowdabanajiga - ಬಲಜಿಗ/ಬಣಜಿಗ/ಗೌಡಬಣಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Naydu - ನಾಯ್ಡು", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Telaga Balija/Telaga Banajiga - ತೆಲಗ ಬಲಿಜ/ತೆಲಗ ಬಣಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Shetty Balija/Shetty Banajiga/Banajiga Shetty - ಶೆಟ್ಟಿ ಬಲಿಜ/ಶೆಟ್ಟಿ ಬಣಜಿಗ/ಬಣಜಿಗ ಶೆಟ್ಟಿ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Dasara Balija/Dasare Baljiga - ದಾಸರ ಬಲಿಜ/ದಾಸರೆ ಬಲಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Dasara Banajiga/Daasa Banajiga - ದಾಸರ ಬಣಜಿಗ/ದಾಸ ಬಣಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Cusban - ಕಸ್ಟನ್", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Munnur/Munnar/Munnur Kaup - ಮುನ್ನೂರ/ಮುನ್ನಾರ್/ಮುನ್ನೂರ್ ಕಾಪು", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Balegara/Bale Banajiga/Bale Baljiga - ಬಳೆಗಾರ/ಬಳೆ ಬಣಜಿಗ/ಬಳೆ ಬಲಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Bale Chetti/Banegara - ಬಳೆ ಚೆಟ್ಟಿ/ ಬಣಗಾರ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Reddy (Balija) - ರೆಡ್ಡಿ (ಬಲಿಜ)", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Janappan - ಜನಪ್ಪನ್", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Uppara (Balija) - ಉಪ್ಪಾರ (ಬಲಿಜ)", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Tulaeru (Balija) - ತುಲೇರು (ಬಲಿಜ)", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Kadugolla - ಕಾಡುಗೊಲ್ಲ", category: "1", nigama: "Kadugoulla" },
  { name: "uppara - ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Belder - ಬೆಲ್ಡರ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Chunaar - ಚುನಾರ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Gaawaadi - ಗಾವಾಡಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Kallu Kutiga Uppara - ಕಲ್ಲು ಕುಟಿಗ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Loonaari - ಲೋನಾರಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Maelu Sakkareyavaru - ಮೇಲು ಸಕ್ಕರೆಯವರು", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Maelu Sakkare - ಮೇಲು ಸಕ್ಕರೆ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Naamada Uppaara - ನಾಮದ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Padit / Padti - ಪಡಿತ್ / ಪಡ್ತಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Padithi - ಪಡಿತಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Paadi - ಪಾಡಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sagara - ಸಗರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sunnagaara - ಸುಣ್ಣಗಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sunna Uppaara - ಸುಣ್ಣ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppaliga - ಉಪ್ಪಳಿಗ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppaligashetti - ಉಪ್ಪಳಿಗಶೆಟ್ಟಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppalian - ಉಪ್ಪಳಿಯನ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppeara - ಉಪ್ಪೇರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Yakalaara - ಯಕಲಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Ekkali - ಎಕ್ಕಲಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Goundi - ಗೌಂದಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Besta - ಬೆಸ್ತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Ambiga/Ambi - ಅಂಬಿಗ/ಅಂಬಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Baarika - ಬಾರಿ/ಬಾರಿಕ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bester - ಬೆಸ್ತರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bhoi - ಭೋಯಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Rajaboi - ರಾಜಬೊಯಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bunde-Beshtar - ಬುಂಡೆ - ಬೆಸ್ಥರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Dalti - ದಾಲ್ಟಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "dawat - ದಾವತ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gabbit - ಗಬಿಟ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Galadkonkani - ಗಲಾಡಕೊಂಕಣಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Ganga makkalu - ಗಂಗಮಕ್ಕಳು", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangakula - ಗಂಗಾಕುಲ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangamata - ಗಂಗಾಮತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangamastha - ಗಂಗಾಮತಸ್ಥ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangaputra - ಗಂಗಾಪುತ್ರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gaurimata - ಗೌರಿಮತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bunde-Besta/Gunde Besta - ಬುಂಡೆ-ಬೆಸ್ತ/ಗುಂಡೆ ಬೆಸ್ತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Harakantra - ಹರಕಂತ್ರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Jalagaara - ಜಲಗಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbera / Kabbear - ಕಬ್ಬೇರ / ಕಬ್ಬರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbaliga - ಕಬ್ಬಲಿಗ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbili - ಕಬ್ಬಿಲಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kahar - ಕಹರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kharvi / Konkan Kharvi - ಖಾರ್ವಿ /ಕೊಂಕಣ ಖಾರ್ವಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Koli - ಕೋಳಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Koli Mahadev - ಕೋಳಿ ಮಹದೇವ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mudder - ಮಡ್ಡರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Meenagar - ಮೀನಗಾ‌ರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mogaveer - ಮೊಗವೀರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mogaer - ಮೊಗೇರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mukkawan - ಮುಕ್ಕವಾನ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Pariwara - ಪರಿವಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Seveyar - ಸಿವಿಯರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Sunagaara - ಸುಣಗಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Tureya - ತೊರೆಯ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Pagi - ಪಾಗಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Jogi - ಜೋಗಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Joshi Sada Joshi - ಜೋಶಿ ಸದ ಜೋಶಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kashikapaddi - ಕಾಶಿಕಪಾಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Katabu - ಕಟಬು", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kel Kari - ಕೆಲ್‌ ಕಾರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Killekyathas - ಕಿಳ್ಳೆಕ್ಯಾತಸ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kolathi - ಕೋಲಾತಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Masani Yogi - ಮಸನಿಯ ಯೋಗಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Nandiwala-Joshi-Ghondal- Pul Malli - ನಂದಿವಾಲ-ಜೋಶಿ-ಘೋಂಡಳ್- ಪುಲ್ ಮಲ್ಲಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Nathapachithi, Dauri Gosavi - ನಾಥಪಚಿಥಿ, ಡೌರಿಗೋಸಾವಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Neer Shikari - ನೀರ್‌ ಶಿಕಾರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Pangul - ಪಂಗುಲ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Pichaguntala - ಪಿಚಗುಂಟಲ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sansiya - ಸನ್‌ಸಿಯ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sarnia - ಸರನಿಯ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sarodi - ಸರೊಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Shikkaligarh - ಶಿಕ್ಕಲಿಗಾರ್‌", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Tirumali - ತಿರುಮಲಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Padi - ಪಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vagri - ವಗ್ರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "wydu - ವೈಡು", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vasudev - ವಾಸುದೇವ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vir - విరో", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Agasa - ಅಗಸ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Chakala - ಚಕಲ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Dhobi - ಧೋಬಿ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Madiwala - ಮಡಿವಾಳ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Mannan - ಮನ್ನನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Parit - ಪರಿತ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Rajaka - ರಾಜಕ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Sakala - ಸಕಲ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Wannan - ವನ್ನನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Welluteddan - ವೆಲ್ಲು ತೇಡನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Sakalavaaddu - ಸಾಕಲವಾಡು", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Pariyala (South Kannada and Udupi District) - ಪರಿಯಾಳ (ದಕ್ಷಿಣ ಕನ್ನಡ ಮತ್ತು ಉಡುಪಿ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Ambattan - ಅಂಬಟ್ಟನ್", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Bajantri - ಬಜಂತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Bhanddari - ಬಂಡಾರಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Chauriya - ಚೌರಿಯ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Kavutian - ಕವುಟಿಯನ್", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Kelasi - ಕೆಲಸಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Kshaurika - ಕ್ಷೌರಿಕ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Kshourad - ಕ್ಷೌರದ್", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Mahale - ಮಹಾಲೆ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Mangala - ಮಂಗಳ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Melagar - ಮೇಲಗಾರ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Naddiga - ನಾಡಿಗ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Napita - ನಾಪಿತ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Navalig - ನವಲಿಗ್", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Navi - ನಾವಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Nayanaja Kshatriya - ನಯನಜ ಕ್ಷತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Nhavi - ನಾವಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Vajantri (North Kannada District) - ವಾಜಾಂತ್ರಿ (ಉತ್ತರ ಕನ್ನಡ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Savita - ಸವಿತ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Nayanaja Kshatriya - ನಯನಜ ಕ್ಷತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Naadiga - ನಾಡಿಗ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Kshourik - ಕ್ಷೌರಿಕ್", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Kshourika - ಕ್ಷೌರಿಕ", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Vishwakarma - ವಿಶ್ವಕರ್ಮ", category: "2A", nigama: "Vishwakarma" },
  { name: "Aachaari - ಆಚಾರಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Akkasaali - ಅಕ್ಕಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Ausaali - ಔಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiger - ಬಡಿಗರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiwadda - ಬಡಿವಾಡ್ಡ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Akkasali - ಬೈಲು ಅಕ್ಕಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Kammaara - ಬೈಲು ಕಮ್ಮಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bogara - ಬೋಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Chappegar - ಚಪ್ಪೇಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Chaarodi - ಚಾರೋಡಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Konkani Aachaara - ಕೊಂಕಣಿ ಆಚಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Dyvagnya Bhramana - ದೈವಜ್ಞಾಬ್ರಾಹ್ಮಣ", category: "2A", nigama: "Vishwakarma" },
  { name: "Gejjegara - ಗೆಜ್ಜೆಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kambar - ಕಂಬಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammalan - ಕಮ್ಮಾಲನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammaara - ಕಮ್ಮಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansala - ಕಂಸಾಳ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansan - ಕಂಸನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchagarh - ಕಂಚಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchora - ಕಂಚೋರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailpatar - ಬೈಲ್‌ಪತರ್‌", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchori - ಕಂಚೋರಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchugaara - ಕಂಚುಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansara - ಕಂಸಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Lohar - ಲೋಹಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Mesta - ಮೆಸ್ತ", category: "2A", nigama: "Vishwakarma" },
  { name: "Panchal - ಪಂಚಾಲ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Pathar - ಪತ್ತರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Sohgar - ಸೋಹಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Silchi - ಸಿಲ್ಚಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kasar - ಕಸಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Sonar - ಸೋನಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Soni - ಸೋನಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Sutar - ಸುತಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Tasehan - ತಸೆಹಾನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "VishwaBrahman - ವಿಶ್ವಬ್ರಾಹ್ಮಣ", category: "2A", nigama: "Vishwakarma" },
  { name: "Thattan - ಥಟ್ಟನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Aksali - ಅಕ್ಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kamsali - ಕಂಸಾಲ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Badagi - ಬಡಗಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Vokkaliga - ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Vokkaliga - ವಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Sarpa Vokkaliga - ಸರ್ಪ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Hallikar Vokkaliga - ಹಳ್ಳಿಕಾರ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Namdhari Vokkaliga - ನಾಮಧಾರಿ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gangadkar Vokkaliga - ಗಂಗಡ್ಕಾರ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Das Vokkaliga - ದಾಸ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Reddy Vokkaliga - ರೆಡ್ಡಿ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Marasu Vokkaliga - ಮರಸು ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gowda - ಗೌಡ", category: "3A", nigama: "Vokkaliga" },
  { name: "Hallikar - ಹಳ್ಳಿಕಾರ್", category: "3A", nigama: "Vokkaliga" },
  { name: "Kunchitiga - ಕುಂಚಿಟಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Kaup - ಕಾಪು", category: "3A", nigama: "Vokkaliga" },
  { name: "Heggade - ಹೆಗ್ಗಡೆ", category: "3A", nigama: "Vokkaliga" },
  { name: "Kamma - ಕಮ್ಮ", category: "3A", nigama: "Vokkaliga" },
  { name: "Raddy - ರಡ್ಡಿ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gounder - ಗೌಂಡರ್", category: "3A", nigama: "Vokkaliga" },
  { name: "Namadhari Gowda - ನಾಮಧಾರಿ ಗೌಡ", category: "3A", nigama: "Vokkaliga" },
  { name: "Uppina Kolaga/ Uttama Kolaga - ಉಪ್ಪಿನ ಕೊಳಗ/ಉತ್ತಮ ಕೊಳಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Veerashaiva Lingayat - ವೀರಶೈವ ಲಿಂಗಾಯತ", category: "3B", nigama: "Veerashaiva Lingayat" },
  { name: "Panchamasali Lingayat - ಪಂಚಮಸಾಲಿ ಲಿಂಗಾಯತ", category: "3B", nigama: "Veerashaiva Lingayat" },
  { name: "Maratha/Marata - ಮರಾತ/ಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Are-Kshatriya/Are-Maratha/Aramarata - ಅರೆ ಕ್ಷತ್ರಿ/ಅರೆ ಮರಾಠ/ಅರಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Arya/Aryaru - ಆರ್ಯ/ಆರ್ಯರು", category: "3B", nigama: "Maratha" },
  { name: "Konkana Maratha - ಕೊಂಕಣ ಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Kshatriya Maratha - ಕ್ಷತ್ರಿಯ ಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Kulwadi - ಕುಳವಾಡಿ", category: "3B", nigama: "Maratha" },
  { name: "Agamudi - ಅಗಮುಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Ambalakaran - ಅಂಬಲಕಾರನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ambalakarma - ಅಂಬಲಕರ್ಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Mutrasi - ಮುತ್ತರಾಸಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Mutracha - ಮುತ್ತರಾಚ", category: "1", nigama: "Devraj Urs" },
  { name: "Baggaru - ಬಗ್ಗರು", category: "1", nigama: "Devraj Urs" },
  { name: "Bavandhi - ಬವಂದಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bavaji - ಬಾವಾಜಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Atit - ಅತಿತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bavani - ಬವಾನಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Byragi - ಬೈರಾಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Davari - ಡವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gosayi - ಗೋಸಾಯಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gusai - ಗುಸಾಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Helova - ಹೆಳೊವ", category: "1", nigama: "Devraj Urs" },
  { name: "Holeva - ಹೊಲೆವ", category: "1", nigama: "Devraj Urs" },
  { name: "Pichigunta - ಪಿಚಿಗುಂಟ", category: "1", nigama: "Devraj Urs" },
  { name: "Pichiguntala - ಪಿಚಿಗುಂಟಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Bava - ಬಾವ", category: "1", nigama: "Devraj Urs" },
  { name: "Byaragi - ಬ್ಯಾರಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhamta - ಭಾಮ್ಟ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhompta - ಭೋಂಪ್ಟ", category: "1", nigama: "Devraj Urs" },
  { name: "Paradeshi-Bhampta - ಪರದೇಶಿ - ಭಾಂಪ್ಟ", category: "1", nigama: "Devraj Urs" },
  { name: "Takari - ಟಕರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhomptra - ಭೋಂಪ್ತç", category: "1", nigama: "Devraj Urs" },
  { name: "Uchillian - ಉಚ್ಚಿಲಿಯನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bhatraju - ಭಾಟ್ರಾಜು", category: "1", nigama: "Devraj Urs" },
  { name: "Bogad - ಬೋಗಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Begadi - ಬೇಗಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bagali - ಬಗಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bogadi - ಬೋಗಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bududki - ಬುಡೂಡ್ಕಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Chhetri - ಚೇಟ್ರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Devari - ದೇವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Garadi - ಗರಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Giddidki - ಗಿಡ್ಡಿಡ್ಕಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kichagara - ಕಿಚಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Modiga - ಮೋದಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Pansa - ಪನ್ಸ", category: "1", nigama: "Devraj Urs" },
  { name: "Panasa - ಪನಸ", category: "1", nigama: "Devraj Urs" },
  { name: "Pingale - ಪಿಂಗಳೆ", category: "1", nigama: "Devraj Urs" },
  { name: "Budbudkala - ಬುಡ್‌ಬುಡಕಾಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Chunchar - ಚುಂಚರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Dasari - ದಾಸರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Dasaru - ದಾಸರು", category: "1", nigama: "Devraj Urs" },
  { name: "Chakravadya-Dasa - ಚಕ್ರವಾದ್ಯ - ದಾಸ", category: "1", nigama: "Devraj Urs" },
  { name: "Dang-Dasar - ದಂಗ್ - ದಾಸರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Devadasi - ದೇವದಾಸಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Basavi - ಬಸವಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhavin - ಭಾವಿನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bogam - ಬೋಗಮ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ganika - ಗಣಿಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Kalavant - ಕಲಾವಂತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Nat - ನಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Natuva - ನಟುವ", category: "1", nigama: "Devraj Urs" },
  { name: "Patramela - ಪತ್ರಮೇಳ", category: "1", nigama: "Devraj Urs" },
  { name: "Ghisade - ಘಿಸಾಡೆ", category: "1", nigama: "Devraj Urs" },
  { name: "Goniga Mane - ಗೋಣಿಗ ಮನೆ", category: "1", nigama: "Devraj Urs" },
  { name: "24 Mane Telugu Shetty - 24 ಮನೆ ತೆಲುಗು ಶೆಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Goni Chetty - ಗೋಣಿಚಿಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Sadusetty - ಸಾದುಸೆಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Salaparu - ಸಲಪರು", category: "1", nigama: "Devraj Urs" },
  { name: "Gurav - ಗುರವ್", category: "1", nigama: "Devraj Urs" },
  { name: "Tamballa - ತಾಂಬಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Tambli - ತಾಂಬ್ಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gurkha - ಗುರ್ಖಾ", category: "1", nigama: "Devraj Urs" },
  { name: "Halawakki Wakkal - ಹಾಲವಕ್ಕಿ ಒಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Halawakki Vakkal - ಹಾಲವಕ್ಕಿ ವಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Atte Vokkalu - ಅಟ್ಟೆಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Gam Gawada - ಗಾಮ್ ಗವಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Gamvokkal - ಗಾಮ್ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Grama Vokkalu - ಗ್ರಾಮ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Halakki Vokkalu - ಹಾಲಕ್ಕಿ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Kare Vokkalu - ಕರೆ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Kunchavakkal - ಕುಂಚ ವಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Shiwakkal - ಶಿಲ್ವಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Vakkal - ವಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gavada - ಗವಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Gam Gawda - ಗಾಮ್ ಗವಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Gram Vakkal - ಗ್ರಾಮ ವಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Hawgar - ಹಾವ್‌ ಗಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Jangala - ಜಂಗಾಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Telugu Jangama - ತೆಲುಗು ಜಂಗಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Pakanathi Jangama - ಪಾಕನಾತಿ ಜಂಗಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Brahma Kapali - ಬ್ರಹ್ಮ ಕಪಾಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Jogar - ಜೋಗಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Jogtin - ಜೋಗ್ತಿನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kapali - ಕಪಾಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Raval - ರಾವಳ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ravalia - ರವಳಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Sanjogi - ಸಂಜೋಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Sanyasi - ಸನ್ಯಾಸಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Joger - ಜೋಗರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjirbhat - ಖಂಜಿರ್ ಭಾಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjar - ಕಂಜರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Khanjar Bhat - ಖಂಜರ್ ಭಾಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kashikapadi - ಕಾಶಿಕಪಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Katabar - ಕಟಬರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Katik - ಕಾಟಿಕ್", category: "1", nigama: "Devraj Urs" },
  { name: "Aray - ಅರೇಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Are Kasai - ಅರೆ ಕಸಾಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ari Katikelu - ಅರಿಕಾಟಿಕೇಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Kalal Khatik - ಕಲಾಲ್ ಖಾಟಿಕ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kasab - ಕಸಾಬ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kasai - ಕಸಾಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Maratti - ಮರಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Suryavamsha Kshatriya - ಸೋಮವಂಶ ಕ್ಷತ್ರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Kodagu Kapala - ಕೊಡುಗು ಕಾಪಾಳ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolari - ಕೊಲಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kalayiri - ಕಲಾಯಿರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Koleri - ಕೊಲೇರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolla - ಕೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Kollala - ಕೊಲ್ಲಾಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Kotari - ಕೊಟಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kotary - ಕೊಟ್ಟಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kottary - ಕೊಟ್ಟಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kottari - ಕೊಟ್ಟಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kudubi - ಕುಡುಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kumbri Marati (Uttra Kannada District) - ಕುಂಬ್ರಿ ಮರಾಠಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kunbi - ಕುಣಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kulwadi - ಕುಳವಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kanbi - ಕಣಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kurma - ಕುರ್ಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Kurmi - ಕುರ್ಮಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Ladaru/Ladara/Ladar - ಲಾಡರು/ಲಾಡರ/ಲಾಡರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Lad/Kshatriya Lad/Sugandhi Lad - ಲಾಡ್/ಕ್ಷತ್ರಿಯಲಾಡ್/ಸುಗಂಧಿಲಾಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Yelegal - ಎಲೆಗಾಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Malaya - ಮಲಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Medara - ಮೇದರ", category: "1", nigama: "Devraj Urs" },
  { name: "Batter - ಬಟ್ಟರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Burned - ಬರ್ನೆಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gouriga - ಗೌವ್ ರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gowri - ಗೌರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gowrimaratha - ಗೌರಿ ಮರಾಠ", category: "1", nigama: "Devraj Urs" },
  { name: "Gowriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Medari - ಮೇದರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Burud - ಬುರುಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Mudhar - ಮುದರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Nairi/Nairy - ನಾಯಿರಿ/ನ್ಯಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Otari - ಒಟರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Pamlor - ಪಾಮ್ಲೋರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Pangusal - ಪಾಂಗ್ಯುಸಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Panika - ಪಣಿಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Raya Rawath - ರಾಯ ರಾವತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ravat - ರಾವತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Reinudas - ರೈನುದಾಸ್", category: "1", nigama: "Devraj Urs" },
  { name: "Satarkar - ಸತಾರ್‌ಕರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Siddi - ಸಿದ್ದಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Sikkaligara - ಸಿಕ್ಕಲಿಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Shikalgar - ಶಿಕ್ಕಲಗಾರ್‌", category: "1", nigama: "Devraj Urs" },
  { name: "Somavamsha Arya Kshatriya - ಸೋಮವಂಶ ಆರ್ಯ ಕ್ಷತ್ರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Chitara - ಚಿತಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Chitragar - ಚಿತ್ರಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Digwan - ದಿಗ್ದಾನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Jeeragara - ಜೀರಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Najabund - ನಾಜಬಂದ್", category: "1", nigama: "Devraj Urs" },
  { name: "Nalabund - ನಾಲಬAದ್", category: "1", nigama: "Devraj Urs" },
  { name: "Tambat - ತಾಂಬಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Takankar - ತಕನ್‌ಕರ", category: "1", nigama: "Devraj Urs" },
  { name: "Tewar - ತೇವರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kalari - ಕಲರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kallar - ಕಲ್ಲರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Maravar - ಮರವರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Tilari - ತಿಲಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Tirali - ತಿರಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Vaidu - ವಾಯ್ಡು", category: "1", nigama: "Devraj Urs" },
  { name: "Vasudev - ವಾಸುದೇವ್", category: "1", nigama: "Devraj Urs" },
  { name: "Veer - ವೀರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Veeramasti - ವೀರಮಸ್ತಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Yeralu - ಏರಾಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Yerkala - ಎರ್‌ಕಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Erakala - ಇರಕಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Kaikadi - ಕೈಕಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Koragar - ಕೊರಗಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kormasetty - ಕೊರ್‌ಮಶೆಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kunchi - ಕುಂಚಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Korwari - ಕೊರ್ವಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Yerukala - ಎರುಕುಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Bailpatar - ಬೈಲ್‌ಪತರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bilapatar - ಬಿಲಪತರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bajenia - ಬಜೆನಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Deria - ಡೇರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhargi - ಭಾರ್‌ಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Chhar - ಚಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Chhara - ಚ್ಚಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Chapper Band (Muslim) - ಚಪ್ಪರ್ ಬಂದ್ (ಮುಸ್ಲಿಂ)", category: "1", nigama: "Devraj Urs" },
  { name: "Chapper Banda - ಚಪ್ಪರ್ ಬಂದ", category: "1", nigama: "Devraj Urs" },
  { name: "Modikara - ಮೋದಿಕಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Modikar - ಮೋದಿಕರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ghondali - ಘೋಂದಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gondaliga - ಗೊಂದಲಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gondhalli - ಗೊಂಧಲ್ಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Javeri - ಜವೇರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Jawari - ಜವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Johari - ಜೋಹರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kamatti - ಕಾಮಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kaman - ಕಮನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjari - ಕಂಜರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjir - ಕಂಜಿರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Khelkari - ಖೇಲ್ಕರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolhatigi - ಕೋಲ್ಹಟಿಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Saranta - ಸಾರಂತ", category: "1", nigama: "Devraj Urs" },
  { name: "Saroda - ಸರೋಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Bedaru - ಬೇಡರು", category: "1", nigama: "Devraj Urs" },
  { name: "Yadav - ಯಾದವ್", category: "1", nigama: "Devraj Urs" },
  { name: "Asthanagolla - ಆಸ್ಥಾನಗೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Yadava - ಯಾದವ", category: "1", nigama: "Devraj Urs" },
  { name: "Adavigolla - ಅಡವಿಗೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Gopali - ಗೋಪಾಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gouli - ಗೌಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauli - ಗಾವ್‌ಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gavali - ಗಾವಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gavli - ಗಾವ್ಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Anubaru - ಅನುಬರು", category: "1", nigama: "Devraj Urs" },
  { name: "Atanabaru - ಅಟನಬರು", category: "1", nigama: "Devraj Urs" },
  { name: "Hanabar - ಹಣಬರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kavadi - ಕಾವಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolayan - ಕೊಲಯನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Konar - ಕೊನಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Konnur - ಕೊನ್ನೂರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Krishna Gavali - ಕೃಷ್ಣ ಗೌಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Krishna Golla - ಕೃಷ್ಣ ಗೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Maniyani - ಮಣಿಯಾನಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Urali - ಉರಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Telugu Gowda (Chickmagalur & Hassan Dists) - ತೆಲುಗು ಗೌಡ (ಚಿಕ್ಕಮಗಳೂರು ಮತ್ತು ಹಾಸನ ಜಿಲ್ಲೆ)", category: "1", nigama: "Devraj Urs" },
  { name: "Banjari - ಬಂಜರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Brinjari - ಬ್ರಿಂಜಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Vanjara - ವಂಜಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Wanjari - ವಂಜಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Lambaid - ಲಂಬೈಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gore or Goria - ಗೋರೆ ಅಥವಾ ಗೋರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Bendar - ಬೆಂಡರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Berad - ಬೆರಾಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Boya - ಬೋಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Naikamakkalu - ನಾಯಕಮಕ್ಕಳು", category: "1", nigama: "Devraj Urs" },
  { name: "Naikwadi - ನಾಯಕ್‌ವಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Palegar - ಪಾಳೇಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Remoshi - ರೆಮೋಶಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Valmikimakkalu - ವಾಲ್ಮೀಕಿ ಮಕ್ಕಳು", category: "1", nigama: "Devraj Urs" },
  { name: "Vedan - ವೇದನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Myasa Nayaka - ಮ್ಯಾಸ ನಾಯಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Urs Nayaka - ಅರಸ್ ನಾಯಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Byada - ಬ್ಯಾಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Haranshikari - ಹರನ್ ಶಿಕಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Chigari Betagar - ಚಿಗರಿ ಬೇಟಗಾರ್", category: "1", nigama: "Devraj Urs" },
  { name: "vaghri - ವಾಘ್ರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Wagiri - ವಾಗರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bargi - ಬಾರ್ಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Baori - ಬೋವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Phasachari - ಘಸಾಚಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Hirshikari - ಹಿರ್ಶಿಕಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Garudiga - ಗಾರುಡಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Garadiga - ಗಾರುಡಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Paradhis - ಪರಧೀಸ್", category: "1", nigama: "Devraj Urs" },
  { name: "Girini waddar - ಗಿರಣಿವಡ್ಡರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Tudug Woddar - ತುಡುಗ್ ವೊಡ್ಡರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bhandi Voddar - ಭಾಂದಿ ವೊಡ್ಡರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bhoi - ಭೋಯಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Boyi - ಬೊಯಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Harikanthra - ಹರಿಕಂತ್ರ", category: "1", nigama: "Devraj Urs" },
  { name: "Kharia - ಖಾರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Bovi - ಬೋವಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Pinjara - ಪಿಂಜಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Pinjari - ಪಿಂಜಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Nadaf - ನದಾಫ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ladaf - ಲದಾಫ್", category: "1", nigama: "Devraj Urs" },
  { name: "Dudekula - ದೂದೇಕುಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Mansoori - ಮನ್ಸೂರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Mansuri - ಮನ್‌ಸೂರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Banna (Kodagu District)", category: "2A", nigama: "Devraj Urs" },
  { name: "Devadiga - ದೇವಾಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devali - ದೇವಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Moyili - ಮೊಯಿಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Padiar", category: "2A", nigama: "Devraj Urs" },
  { name: "Seregara - ಸೇರೆಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Servegar", category: "2A", nigama: "Devraj Urs" },
  { name: "Sheregar", category: "2A", nigama: "Devraj Urs" },
  { name: "Suplig", category: "2A", nigama: "Devraj Urs" },
  { name: "Kodagu Heggade (Kodagu Dist)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruba - ಕುರುಬ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Bharwad", category: "2A", nigama: "Devraj Urs" },
  { name: "Dhanagar - ಧನಗರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Goraya", category: "2A", nigama: "Devraj Urs" },
  { name: "Halumatha", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurab - ಕುರಬ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurauban", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurumba - ಕುರುಂಬ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurub", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurumban", category: "2A", nigama: "Devraj Urs" },
  { name: "Aghori - ಅಘೋರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Karakarmunda", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnani", category: "2A", nigama: "Devraj Urs" },
  { name: "Ambalavasi - ಅಂಬಲವಾಸಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Anduran - ಅಂಡೂರನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Atari", category: "2A", nigama: "Devraj Urs" },
  { name: "Athari - ಅಥರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bahurupi", category: "2A", nigama: "Devraj Urs" },
  { name: "Bakadra - ಬಕದ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bathal", category: "2A", nigama: "Devraj Urs" },
  { name: "Battal - ಬಟ್ಟಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Batter", category: "2A", nigama: "Devraj Urs" },
  { name: "Bawtar", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhaat", category: "2A", nigama: "Devraj Urs" },
  { name: "Bohrot", category: "2A", nigama: "Devraj Urs" },
  { name: "Binapatta - ಬಿನ್ನಪಟ್ಟ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bingi - బింగి", category: "2A", nigama: "Devraj Urs" },
  { name: "Bagadi - ಬಗಾಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bagaadi", category: "2A", nigama: "Devraj Urs" },
  { name: "Bagdi - ಬಗ್ಗಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chaliyan", category: "2A", nigama: "Devraj Urs" },
  { name: "Teruvan", category: "2A", nigama: "Devraj Urs" },
  { name: "Challiya - ಚಲ್ಲಿ ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chamboti - ಚಂಬೋಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chambukutti", category: "2A", nigama: "Devraj Urs" },
  { name: "Mestha", category: "2A", nigama: "Devraj Urs" },
  { name: "Jingar", category: "2A", nigama: "Devraj Urs" },
  { name: "Ghadi - ಘಾಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gadiga - ಗಾಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gunagi - ಗುನಗಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ghadsi - ಘಾಡ್ಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ghadshi", category: "2A", nigama: "Devraj Urs" },
  { name: "Pingle", category: "2A", nigama: "Devraj Urs" },
  { name: "Gosavi - ಗೋಸಾವಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gosain", category: "2A", nigama: "Devraj Urs" },
  { name: "Gujar - ಗುಜಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Guzar", category: "2A", nigama: "Devraj Urs" },
  { name: "Gurava - ಗುರವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gurou", category: "2A", nigama: "Devraj Urs" },
  { name: "Gabbit - ಗಬಿಟ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gapit - ಗಪಿಟ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gaabit", category: "2A", nigama: "Devraj Urs" },
  { name: "Daalija", category: "2A", nigama: "Devraj Urs" },
  { name: "Handevazir", category: "2A", nigama: "Devraj Urs" },
  { name: "Handervut", category: "2A", nigama: "Devraj Urs" },
  { name: "Honniyar", category: "2A", nigama: "Devraj Urs" },
  { name: "Hoovadiga", category: "2A", nigama: "Devraj Urs" },
  { name: "Hugar", category: "2A", nigama: "Devraj Urs" },
  { name: "Hoogar", category: "2A", nigama: "Devraj Urs" },
  { name: "Maalgar", category: "2A", nigama: "Devraj Urs" },
  { name: "Mali", category: "2A", nigama: "Devraj Urs" },
  { name: "Phool Mali", category: "2A", nigama: "Devraj Urs" },
  { name: "Phul Mali", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulari", category: "2A", nigama: "Devraj Urs" },
  { name: "Phoolari", category: "2A", nigama: "Devraj Urs" },
  { name: "Jeer - ಜೀರಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kadu Konkani", category: "2A", nigama: "Devraj Urs" },
  { name: "Karikudumbi - ಕರಿಕುಡು೦ಬಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Karuva - ಕರುವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Khatik", category: "2A", nigama: "Devraj Urs" },
  { name: "Katuka", category: "2A", nigama: "Devraj Urs" },
  { name: "Katuga - ಕಟುಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bogara - ಬೋಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kasbin", category: "2A", nigama: "Devraj Urs" },
  { name: "Kolayiri - ಕೊಲಾಯಿರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kolyiri - ಕೊಲ್ಯಿರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanisan - ಕಣಿಸನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Balyaya (Dakshina Kannada & Udupi Dist)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniyar - ಕಣಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniyaru - ಕಣಿಯರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniya - ಕಣಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniyan (Other than Kollegal Taluk of Mysore Dist)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanyan - ಕನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kutuma - ಕುಟುಮ", category: "2A", nigama: "Devraj Urs" },
  { name: "Marta - ಮರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Marayan - ಮರಯನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Maravan - ಮರವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Murrari - ಮುದ್ರಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadora", category: "2A", nigama: "Devraj Urs" },
  { name: "Uppu Nadar/Upa Nador", category: "2A", nigama: "Devraj Urs" },
  { name: "Torke Nador - ತೊರ್ಕೆ ನಾಡೋರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadavar - ನಾಡವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Uppunador/Upa Nadavar", category: "2A", nigama: "Devraj Urs" },
  { name: "Nalki", category: "2A", nigama: "Devraj Urs" },
  { name: "Osthan", category: "2A", nigama: "Devraj Urs" },
  { name: "Pandaram", category: "2A", nigama: "Devraj Urs" },
  { name: "Pandar", category: "2A", nigama: "Devraj Urs" },
  { name: "Pandara - ಪಂಡಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Panaba", category: "2A", nigama: "Devraj Urs" },
  { name: "Pannekara Konkani", category: "2A", nigama: "Devraj Urs" },
  { name: "Patra", category: "2A", nigama: "Devraj Urs" },
  { name: "Pichati", category: "2A", nigama: "Devraj Urs" },
  { name: "Pullavan", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajapuri - ರಾಜಪುರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajpur", category: "2A", nigama: "Devraj Urs" },
  { name: "Balavalikar", category: "2A", nigama: "Devraj Urs" },
  { name: "Saniyaar", category: "2A", nigama: "Devraj Urs" },
  { name: "Shanan - ಶಾನನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Sudir - ಸುದಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sudra - ಸೂದ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kulawadi Marati", category: "2A", nigama: "Devraj Urs" },
  { name: "Sutsali", category: "2A", nigama: "Devraj Urs" },
  { name: "Tachayiri - ತಚಾಯಿರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tilvi", category: "2A", nigama: "Devraj Urs" },
  { name: "Gavandi - ಗವಂಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Govandi - ಗೋವಂಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Vettuvan - ವೆಟ್ಟುವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Yeklar", category: "2A", nigama: "Devraj Urs" },
  { name: "Yaklar - ಯಕ್ಷ", category: "2A", nigama: "Devraj Urs" },
  { name: "Egalika", category: "2A", nigama: "Devraj Urs" },
  { name: "Gatti/ Gattiyavaru", category: "2A", nigama: "Devraj Urs" },
  { name: "Poledava / Poladavaru", category: "2A", nigama: "Devraj Urs" },
  { name: "Gudigara - ಗುಡಿಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Darji - ದರ್ಜಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhavasar Kshatriya", category: "2A", nigama: "Devraj Urs" },
  { name: "Chippi - ಚಿಪ್ಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chippiga - ಚಿಪ್ಪಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Simpi - ಶಿಂಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Shimpi - ಶಿಂಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sai", category: "2A", nigama: "Devraj Urs" },
  { name: "Miral - ಮಿರಾಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Rangari - ರಂಗಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rangrez", category: "2A", nigama: "Devraj Urs" },
  { name: "Nilari - ನಿಲಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Namdev", category: "2A", nigama: "Devraj Urs" },
  { name: "Namdev Simpi", category: "2A", nigama: "Devraj Urs" },
  { name: "Rangare - ರಂಗಾರೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Neelagar - ನೀಲಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devanga - ದೇವಾಂಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devang - ದೇವಾಂಗ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Koshti - ಕೋಷ್ಠಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hutgar/Hutkar", category: "2A", nigama: "Devraj Urs" },
  { name: "Jed", category: "2A", nigama: "Devraj Urs" },
  { name: "Winkar", category: "2A", nigama: "Devraj Urs" },
  { name: "Julohi", category: "2A", nigama: "Devraj Urs" },
  { name: "Hulkar", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagar", category: "2A", nigama: "Devraj Urs" },
  { name: "Neygi", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruhina Setty", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurni - ಕುರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "BiliMagga", category: "2A", nigama: "Devraj Urs" },
  { name: "Thogata / Thogataru/ Thogatiga/ Thogataveera/ Thogatagera/ Thogataveer Kshatriya/ Thogaja Pushpanjali", category: "2A", nigama: "Devraj Urs" },
  { name: "Soniga - ಸೋಣಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jam Khana", category: "2A", nigama: "Devraj Urs" },
  { name: "Ayiri", category: "2A", nigama: "Devraj Urs" },
  { name: "Avir - ಅವಿರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sale/ Patta Sale", category: "2A", nigama: "Devraj Urs" },
  { name: "Padma Sale/ Padma Shali/ Padma Sali", category: "2A", nigama: "Devraj Urs" },
  { name: "Saale/Pattasali", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaikolan/Sengundhar", category: "2A", nigama: "Devraj Urs" },
  { name: "Neikar", category: "2A", nigama: "Devraj Urs" },
  { name: "Jadar", category: "2A", nigama: "Devraj Urs" },
  { name: "Jandra", category: "2A", nigama: "Devraj Urs" },
  { name: "Swakula Sali/Swakula Sale", category: "2A", nigama: "Devraj Urs" },
  { name: "Pattegar", category: "2A", nigama: "Devraj Urs" },
  { name: "Patvekari", category: "2A", nigama: "Devraj Urs" },
  { name: "Somavamsha Sahasrajuna Kshatriya", category: "2A", nigama: "Devraj Urs" },
  { name: "Amma Kodava - ಅಮ್ಮ ಕೊಡವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Anappan", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajaput", category: "2A", nigama: "Devraj Urs" },
  { name: "Andi - ಆಂಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Andipandaram - ಆಂಡಿಪಂಡಾರಂ", category: "2A", nigama: "Devraj Urs" },
  { name: "Baandhi", category: "2A", nigama: "Devraj Urs" },
  { name: "Bolahallala - ಬೋಲಹಳ್ಳಾಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ballala - ಬಲ್ಲಾಳ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhatial", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhattia", category: "2A", nigama: "Devraj Urs" },
  { name: "Chakkan - ಚಕ್ಕನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Dogra - ಡೋಗ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gulli - ಗುಳ್ಳಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hindu Sadru/Sadaru/Sadumata/Sadkula/Sadar/Sadu Gowda/Sadu Gowdar/Sadara/Sadari/Sadara Gowda", category: "2A", nigama: "Devraj Urs" },
  { name: "Jetti/Jatti - ಜೆಟ್ಟಿ/ಜಟ್ಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Mallaru Malla Kshatriya - ಮಲ್ಲಾರು ಮಲ್ಲ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Mushtiga - ಮುಷ್ಠಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kalavanthi", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhogam/Teluga", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanakan - ಕನಕನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanakar - ಕನಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Karunika - ಕರುಣಿಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kotegar", category: "2A", nigama: "Devraj Urs" },
  { name: "Koteyar", category: "2A", nigama: "Devraj Urs" },
  { name: "Kothati - ಕೊಥಾಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kottegara - ಕೊಟ್ಟೇಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kotteyara", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumara Kshatriya", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumara Panth/Komarpant/Komarpaik Kshatriya Komarpant", category: "2A", nigama: "Devraj Urs" },
  { name: "Rama Kshatriya - ರಾಮ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rama Raj Kshatriya", category: "2A", nigama: "Devraj Urs" },
  { name: "Serugara (North Kanara)", category: "2A", nigama: "Devraj Urs" },
  { name: "Servgar (South Kanara)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kote Kshatriya - ಕೋಟೆ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kshatriya/Kshatri", category: "2A", nigama: "Devraj Urs" },
  { name: "Malawa", category: "2A", nigama: "Devraj Urs" },
  { name: "Maleya - ಮಲೆಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Aryan", category: "2A", nigama: "Devraj Urs" },
  { name: "Raju Kshatriya - ರಾಜು ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Raju-Raju", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajuwar/Rajavar/Rachevar", category: "2A", nigama: "Devraj Urs" },
  { name: "Somavamsha Kshatriya - ಸೋಮವಂಶ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Stanika", category: "2A", nigama: "Devraj Urs" },
  { name: "Tulu - ತುಳು", category: "2A", nigama: "Devraj Urs" },
  { name: "Tuluva", category: "2A", nigama: "Devraj Urs" },
  { name: "Ushtama (Dharwar, Belgaum, Bijapur Gadag Dist)", category: "2A", nigama: "Devraj Urs" },
  { name: "Arasu,Urs - ಅರಸು,ಅರಸ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Balija - ಬಲಿಜ", category: "3A", nigama: "Devraj Urs" },
  { name: "Balajiga/Banajiga/Gowda Banajiga", category: "3A", nigama: "Devraj Urs" },
  { name: "Naidu", category: "3A", nigama: "Devraj Urs" },
  { name: "Telaga Balija/telaga Banajiga - ತೆಲಗ ಬಲಿಜ/ತೆಲಗ ಬಣಜಿಗ", category: "3A", nigama: "Devraj Urs" },
  { name: "Setty Balija/Setty Banajiga/Banajiga Setty", category: "3A", nigama: "Devraj Urs" },
  { name: "Dasara Balija/Dasra Balajiga/Dasara Banajiga/Dasa Banajiga", category: "3A", nigama: "Devraj Urs" },
  { name: "Kasban", category: "3A", nigama: "Devraj Urs" },
  { name: "Munnur/Munnar/Munnur Kapu", category: "3A", nigama: "Devraj Urs" },
  { name: "Balegara/Bale Banajiga/Bale Balajiga/Bale Chetty/Banagara", category: "3A", nigama: "Devraj Urs" },
  { name: "Reddy (Balija) - ರೆಡ್ಡಿ (ಬಲಿಜ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Janappan - ಜನಪ್ಪನ್", category: "3A", nigama: "Devraj Urs" },
  { name: "Uppar (Balija)", category: "3A", nigama: "Devraj Urs" },
  { name: "Tuleru (Balija)", category: "3A", nigama: "Devraj Urs" },
  { name: "Bunt/Bant", category: "3B", nigama: "Devraj Urs" },
  { name: "Parivara Bant", category: "3B", nigama: "Devraj Urs" },
  { name: "Satani", category: "3B", nigama: "Devraj Urs" },
  { name: "Chattada Srivaishnava/ Chattada Vaishnava/Sattada Vaishnava/Sattada Srivaishnava", category: "3B", nigama: "Devraj Urs" },
  { name: "Kadri Vaishnava", category: "3B", nigama: "Devraj Urs" },
  { name: "Sameraya", category: "3B", nigama: "Devraj Urs" },
  { name: "Sattadaval", category: "3B", nigama: "Devraj Urs" },
  { name: "Sattadavan", category: "3B", nigama: "Devraj Urs" },
  { name: "Vaishnava", category: "3B", nigama: "Devraj Urs" },
] as const;

export const CASTE_NAMES = CASTES.map((c) => c.name);

export const CASTE_CATEGORIES = Array.from(new Set(CASTES.map((c) => c.category))).filter((cat) => cat !== "nan" && cat !== "NaN");

export const NIGAMAS = Array.from(new Set(CASTES.map((c) => c.nigama))).filter((nig) => nig !== "nan" && nig !== "NaN");

export const NIGAMA_ALIASES: Record<string, readonly string[]> = {
  "Devraj Urs": [
    "Devraj Urs",
    "DEVRAJ URS",
    "devraj urs",
    "D. Devaraj Urs",
    "D. Devaraj Urs Backward Classes Development Corporation",
    "ಡಿ. ದೇವರಾಜ ಅರಸು ಹಿಂದುಳಿದ ವರ್ಗಗಳ ಅಭಿವೃದ್ಧಿ ನಿಗಮ",
    "ಡಿ.ದೇವರಾಜ ಅರಸು ಹಿಂದುಳಿದ ವರ್ಗಗಳ ಅಭಿವೃದ್ಧಿ ನಿಗಮ",
  ],
  "Vokkaliga": ["Vokkaliga", "VOKKALIGA", "vokkaliga"],
  "Veerashaiva Lingayat": ["Veerashaiva Lingayat", "Veerashaiva Lingayath", "LINGAYAT", "LINGAYATH", "Lingayat", "Lingayath"],
  "Savita Samaaja Abhivrudhi": ["Savita Samaaja Abhivrudhi", "Savita Samaaja Abivrudhi"],
};

export function normalizeNigamaName(rawName?: string | null): string {
  if (!rawName) return "";
  const trimmed = rawName.trim();
  if (!trimmed) return "";

  for (const [canonical, aliases] of Object.entries(NIGAMA_ALIASES)) {
    if (canonical.toLowerCase() === trimmed.toLowerCase()) return canonical;
    if (aliases.some((a) => a.toLowerCase() === trimmed.toLowerCase())) {
      return canonical;
    }
  }

  // Exact match with known NIGAMAS
  const known = NIGAMAS.find((n) => n.toLowerCase() === trimmed.toLowerCase());
  if (known) return known;

  return trimmed;
}

export function getNigamaAliases(canonicalName: string): string[] {
  const trimmed = canonicalName.trim();
  for (const [canonical, aliases] of Object.entries(NIGAMA_ALIASES)) {
    if (canonical.toLowerCase() === trimmed.toLowerCase()) {
      return Array.from(new Set([canonical, ...aliases]));
    }
  }
  return [canonicalName];
}

export function getCasteCertificateType(
  category?: string | null,
  subCategory?: string | null,
  casteName?: string | null,
): string {
  const cat = (category || "").trim();
  const sub = (subCategory || "").trim().toUpperCase();

  if (cat.toLowerCase() === "general") {
    return "";
  }

  // If subCategory or category is explicitly Category 1
  if (sub === "1" || sub === "CAT-1" || sub === "CAT 1" || sub === "CATEGORY 1" || cat === "1" || cat === "Cat-1") {
    return "Form-F (Category 1)";
  }

  // If subCategory is 2A, 2B, 3A, 3B
  if (["2A", "2B", "3A", "3B"].includes(sub)) {
    return `Form-E (Category ${sub})`;
  }

  // If category is SC or ST
  if (cat.toUpperCase() === "SC" || sub === "SC") {
    return "Form-D (SC)";
  }
  if (cat.toUpperCase() === "ST" || sub === "ST") {
    return "Form-D (ST)";
  }

  // Fallback check from casteName in CASTES list
  if (casteName) {
    const found = CASTES.find(
      (c) =>
        c.name.toLowerCase() === casteName.trim().toLowerCase() ||
        c.name.split(" - ")[0]?.trim().toLowerCase() === casteName.trim().toLowerCase(),
    );
    if (found && found.category) {
      const foundCat = found.category.trim().toUpperCase();
      if (foundCat === "1") return "Form-F (Category 1)";
      if (["2A", "2B", "3A", "3B"].includes(foundCat)) return `Form-E (Category ${foundCat})`;
    }
  }

  // Default for OBC
  if (cat === "OBC") {
    return "Form-E (Income & Caste)";
  }

  return "";
}
