export type CasteEntry = { name: string; category: string; nigama: string };

export const CASTES: readonly CasteEntry[] = [
  { name: "Ganiga - ಗಾಣಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Teli - ತೇಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gandla - ಗಾಂಡ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Vaniyan - ವನಿಯನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Jyothi Nagar/Jyothi Nagar Vyshya - ಜ್ಯೋತಿನಗರ/ಜ್ಯೋತಿನಗರ ವ್ಯಶ್ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ediga - ಈಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bandhari - ಬಂಧಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Belbad - ಬೆಲ್ಬದ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Billava - ಬಿಲ್ಲವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Pujari - ಪೂಜಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Divara - ದೀವರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hala Kshatriya - ಹಾಲ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Desh Bhandari - ದೇಶ ಭಂಡಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devara - ದೇವರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devara Makkalu / Deevara Makkalu - ದೇವರ ಮಕ್ಕಳು/ದೀವರ ಮಕ್ಕಳು", category: "2A", nigama: "Devraj Urs" },
  { name: "Aeliga - ಎಳಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Aelava - ಎಳವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gamalla - ಗಾಮಲ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Goundla - ಗೌಂಡ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Paikaru - ಹಳೇ ಪೈಕರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Pike - ಹಳೇ ಪೈಕ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Illavan - ಇಲ್ಲಾವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kalal - ಕಲಾಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Malayali Billava - ಮಲಯಾಳಿ ಬಿಲ್ಲವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Naadar - ನಾಡರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Naamadhari - ನಾಮಧಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Thiyaan/Thiyya - ಥಿಯಾನ್/ಥಿಯ್ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Iliga - ಇಳಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gondla - ಗೊಂಡ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tiyan/Thiyyaan - ತಿಯನ್/ಥಿಯ್ಯಾನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Daevanga - ದೇವಾಂಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Daevang - ದೇವಾಂಗ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Koshti - ಕೋಷ್ಠಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagaar - ಹಟಗಾರ್/ಹಟಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Jade - ಜೇಡ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Winkaar - ವಿಂಕಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Juloohi - ಜುಲೋಹಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Halkaar - ಹಲ್ಕಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagaar - ಹಟಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Naeyke - ನೇಯ್ದೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruhina Shetty - ಕುರುಹಿನ ಶೆಟ್ಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurni - ಕುರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bili Magga - ಬಿಳಿಮಗ್ಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togata/ Toogataru/ Togatiga - ತೊಗಟ/ತೊಗಟರು/ತೊಗಟಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togataweera/Togatagera - ತೊಗಟವೀರ/ತೊಗಟಗೇರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togatavira Kshatriya/Togaja Pushpanjali - ತೊಗಟವೀರ ಕ್ಷತ್ರಿಯ/ತೊಗಜ ಪುಷ್ಪಾಂಜಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sooniga - ಸೋಣಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jankhana - ಜಂಖಾನ", category: "2A", nigama: "Devraj Urs" },
  { name: "Airi - ఐరి", category: "2A", nigama: "Devraj Urs" },
  { name: "Avir - అవిరో", category: "2A", nigama: "Devraj Urs" },
  { name: "Saale: Pattasaalae - ಸಾಲೆ:ಪಟ್ಟಸಾಲೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Padmasaalae/Padmashaali/Padmasaali - ಪದ್ಮಸಾಲೆ/ಪದ್ಮಶಾಲಿ/ ಪದ್ಮಸಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saali/Pattasaali - ಸಾಲಿ/ಪಟ್ಟಸಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaikoolan/Sengunder - ಕೈಕೋಳನ್/ಸೆಂಗುಂದರ್‌", category: "2A", nigama: "Devraj Urs" },
  { name: "Neykaar - ನೇಯ್ಕಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Jaadar - ಜಾಡರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Chandra - ಚಾಂದ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Svakulasali/Svakulsali - ಸ್ವಕುಳಸಾಳಿ/ಸ್ವಕುಳಸಾಳೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbar - ಕುಂಬಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chakrasali - ಚಕ್ರಸಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gunga - ಗುಣಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ganagi - ಗಣಗಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Koyava - ಕೊಯವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kula - ಕುಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kulaala - ಕುಲಾಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbaar - ಕುಂಬಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "kumbaarda - ಕುಂಬಾರ್ಡ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kummaara - ಕುಮ್ಮಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kusavan - ಕುಸವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Maulya - ಮೂಲ್ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sajjana Kumbaara - ಸಜ್ಜನ ಕುಂಬಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Khumaara - ಖುಮಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbhara - ಕುಂಭಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Khumbhaara - ಖುಂಭಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kulaalar - ಕುಲಾಲರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Tigala - ತಿಗಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnivamsha - ಅಗ್ನಿವಂಶ", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnivanni - ಅಗ್ನಿವನ್ನಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnikulakshatriya - ಅಗ್ನಿಕುಲಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Dharmaraja Kaapu - ಧರ್ಮರಾಜ ಕಾಪು", category: "2A", nigama: "Devraj Urs" },
  { name: "Palli - ಪಳ್ಳಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Shambhukulakshatriya - ಶಂಭುಕುಲ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tigala - ತಿಗಳ", category: "2A", nigama: "Devraj Urs" },
  { name: "Vanniyar - ವನ್ನಿಯರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Vannikulakshatriya - ವನ್ನಿಕುಲಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tiglar - ತಿಗ್ಗರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuroovan - ಕುರೋವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Hadapada - ಹಡಪದ", category: "2A", nigama: "Devraj Urs" },
  { name: "Huvaadiga - ಹೂವಾಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hugaar - ಹುಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Huugaar - ಹೂಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Malgaar - ಮಾಲಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Maali - ಮಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Moolmali - ಮೂಲ್‌ಮಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulmali - ಫುಲ್‌ಮಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulaari - ಫುಲಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Phalaari - ಫಲಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jeer - జిరా", category: "2A", nigama: "Devraj Urs" },
  { name: "Balija - ಬಲಿಜ", category: "3A", nigama: "Devraj Urs" },
  { name: "Balajiga/Banajiga/Gowdabanajiga - ಬಲಜಿಗ/ಬಣಜಿಗ/ಗೌಡಬಣಜಿಗ", category: "3A", nigama: "Devraj Urs" },
  { name: "Naydu - ನಾಯ್ಡು", category: "3A", nigama: "Devraj Urs" },
  { name: "Telaga Balija/Telaga Banajiga - ತೆಲಗ ಬಲಿಜ/ತೆಲಗ ಬಣಜಿಗ", category: "3A", nigama: "Devraj Urs" },
  { name: "Shetty Balija/Shetty Banajiga/Banajiga Shetty - ಶೆಟ್ಟಿ ಬಲಿಜ/ಶೆಟ್ಟಿ ಬಣಜಿಗ/ಬಣಜಿಗ ಶೆಟ್ಟಿ", category: "3A", nigama: "Devraj Urs" },
  { name: "Dasara Balija/Dasare Baljiga - ದಾಸರ ಬಲಿಜ/ದಾಸರೆ ಬಲಜಿಗ", category: "3A", nigama: "Devraj Urs" },
  { name: "Dasara Banajiga/Daasa Banajiga - ದಾಸರ ಬಣಜಿಗ/ದಾಸ ಬಣಜಿಗ", category: "3A", nigama: "Devraj Urs" },
  { name: "Cusban - ಕಸ್ಟನ್", category: "3A", nigama: "Devraj Urs" },
  { name: "Munnur/Munnar/Munnur Kaup - ಮುನ್ನೂರ/ಮುನ್ನಾರ್/ಮುನ್ನೂರ್ ಕಾಪು", category: "3A", nigama: "Devraj Urs" },
  { name: "Balegara/Bale Banajiga/Bale Baljiga - ಬಳೆಗಾರ/ಬಳೆ ಬಣಜಿಗ/ಬಳೆ ಬಲಜಿಗ", category: "3A", nigama: "Devraj Urs" },
  { name: "Bale Chetti/Banegara - ಬಳೆ ಚೆಟ್ಟಿ/ ಬಣಗಾರ", category: "3A", nigama: "Devraj Urs" },
  { name: "Reddy (Balija) - ರೆಡ್ಡಿ (ಬಲಿಜ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Janappan - ಜನಪ್ಪನ್", category: "3A", nigama: "Devraj Urs" },
  { name: "Uppara (Balija) - ಉಪ್ಪಾರ (ಬಲಿಜ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Tulaeru (Balija) - ತುಲೇರು (ಬಲಿಜ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Kodagaru - ಕೊಡಗರು", category: "3A", nigama: "Devraj Urs" },
  { name: "Maedara - ಮೇದರ", category: "1", nigama: "Devraj Urs" },
  { name: "Battar - బట్టిరో", category: "1", nigama: "Devraj Urs" },
  { name: "Burned - ಬರ್ನೆಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauv Rigga - ಗೌವ್ ರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauri - గౌరి", category: "1", nigama: "Devraj Urs" },
  { name: "Gauri Marata - ಗೌರಿ ಮರಾಠ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Maedari - ಮೇದರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Burud - ಬುರುಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kadugolla - ಕಾಡುಗೊಲ್ಲ", category: "1", nigama: "Kadugoulla" },
  { name: "uppara - ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Belder - ಬೆಲ್ಡರ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Chunaar - ಚುನಾರ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Gaawaadi - ಗಾವಾಡಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Kallu Kutiga Uppara - ಕಲ್ಲು ಕುಟಿಗ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Loonaari - ಲೋನಾರಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Maelu Sakkareyavaru - ಮೇಲು ಸಕ್ಕರೆಯವರು", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Maelu Sakkare - ಮೇಲು ಸಕ್ಕರೆ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Naamada Uppaara - ನಾಮದ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Padit / Padti - ಪಡಿತ್ / ಪಡ್ತಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Padithi - ಪಡಿತಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Paadi - ಪಾಡಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sagara - ಸಗರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sunnagaara - ಸುಣ್ಣಗಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sunna Uppaara - ಸುಣ್ಣ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppaliga - ಉಪ್ಪಳಿಗ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppaligashetti - ಉಪ್ಪಳಿಗಶೆಟ್ಟಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppalian - ಉಪ್ಪಳಿಯನ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppeara - ಉಪ್ಪೇರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Yakalaara - ಯಕಲಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Ekkali - ಎಕ್ಕಲಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Goundi - ಗೌಂದಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Besta - ಬೆಸ್ತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Ambiga/Ambi - ಅಂಬಿಗ/ಅಂಬಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Baarika - ಬಾರಿ/ಬಾರಿಕ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bester - ಬೆಸ್ತರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bhoi - ಭೋಯಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Rajaboi - ರಾಜಬೊಯಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bunde-Beshtar - ಬುಂಡೆ - ಬೆಸ್ಥರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Dalti - ದಾಲ್ಟಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "dawat - ದಾವತ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gabbit - ಗಬಿಟ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Galadkonkani - ಗಲಾಡಕೊಂಕಣಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Ganga makkalu - ಗಂಗಮಕ್ಕಳು", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangakula - ಗಂಗಾಕುಲ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangamata - ಗಂಗಾಮತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangamastha - ಗಂಗಾಮತಸ್ಥ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangaputra - ಗಂಗಾಪುತ್ರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gaurimata - ಗೌರಿಮತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bunde-Besta/Gunde Besta - ಬುಂಡೆ-ಬೆಸ್ತ/ಗುಂಡೆ ಬೆಸ್ತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Harakantra - ಹರಕಂತ್ರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Jalagaara - ಜಲಗಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbera / Kabbear - ಕಬ್ಬೇರ / ಕಬ್ಬರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbaliga - ಕಬ್ಬಲಿಗ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbili - ಕಬ್ಬಿಲಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kahar - ಕಹರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kharvi / Konkan Kharvi - ಖಾರ್ವಿ /ಕೊಂಕಣ ಖಾರ್ವಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Koli - ಕೋಳಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Koli Mahadev - ಕೋಳಿ ಮಹದೇವ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mudder - ಮಡ್ಡರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Meenagar - ಮೀನಗಾ‌ರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mogaveer - ಮೊಗವೀರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mogaer - ಮೊಗೇರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mukkawan - ಮುಕ್ಕವಾನ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Pariwara - ಪರಿವಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Seveyar - ಸಿವಿಯರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Sunagaara - ಸುಣಗಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Tureya - ತೊರೆಯ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Pagi - ಪಾಗಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Jogi - ಜೋಗಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Joshi Sada Joshi - ಜೋಶಿ ಸದ ಜೋಶಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kashikapaddi - ಕಾಶಿಕಪಾಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Katabu - ಕಟಬು", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kel Kari - ಕೆಲ್‌ ಕಾರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Killekyathas - ಕಿಳ್ಳೆಕ್ಯಾತಸ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kolathi - ಕೋಲಾತಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Masani Yogi - ಮಸನಿಯ ಯೋಗಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Nandiwala-Joshi-Ghondal- Pul Malli - ನಂದಿವಾಲ-ಜೋಶಿ-ಘೋಂಡಳ್- ಪುಲ್ ಮಲ್ಲಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Nathapachithi, Dauri Gosavi - ನಾಥಪಚಿಥಿ, ಡೌರಿಗೋಸಾವಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Neer Shikari - ನೀರ್‌ ಶಿಕಾರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Pangul - ಪಂಗುಲ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Pichaguntala - ಪಿಚಗುಂಟಲ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sansiya - ಸನ್‌ಸಿಯ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sarnia - ಸರನಿಯ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sarodi - ಸರೊಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Shikkaligarh - ಶಿಕ್ಕಲಿಗಾರ್‌", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Tirumali - ತಿರುಮಲಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Padi - ಪಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vagri - ವಗ್ರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "wydu - ವೈಡು", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vasudev - ವಾಸುದೇವ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vir - విరో", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Agasa - ಅಗಸ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Chakala - ಚಕಲ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Dhobi - ಧೋಬಿ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Madiwala - ಮಡಿವಾಳ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Mannan - ಮನ್ನನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Parit - ಪರಿತ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Rajaka - ರಾಜಕ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Sakala - ಸಕಲ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Wannan - ವನ್ನನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Welluteddan - ವೆಲ್ಲು ತೇಡನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Sakalavaaddu - ಸಾಕಲವಾಡು", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Pariyala (South Kannada and Udupi District) - ಪರಿಯಾಳ (ದಕ್ಷಿಣ ಕನ್ನಡ ಮತ್ತು ಉಡುಪಿ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Ambattan - ಅಂಬಟ್ಟನ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Bajantri - ಬಜಂತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Bhanddari - ಬಂಡಾರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Chauriya - ಚೌರಿಯ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kavutian - ಕವುಟಿಯನ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kelasi - ಕೆಲಸಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshaurika - ಕ್ಷೌರಿಕ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshourad - ಕ್ಷೌರದ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Mahale - ಮಹಾಲೆ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Mangala - ಮಂಗಳ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Melagar - ಮೇಲಗಾರ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Naddiga - ನಾಡಿಗ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Napita - ನಾಪಿತ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Navalig - ನವಲಿಗ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Navi - నావి", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Nayanaja Kshatriya - ನಯನಜ ಕ್ಷತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Nhavi - నావి", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Vajantri (North Kannada District) - ವಾಜಾಂತ್ರಿ (ಉತ್ತರ ಕನ್ನಡ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Savita - ಸವಿತ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Nayanaja Kshatriya - ನಯನಜ ಕ್ಷತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Naadiga - నాడిగా", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshourik - ಕ್ಷೌರಿಕ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshourika - ಕ್ಷೌರಿಕ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Vishwakarma - ವಿಶ್ವಕರ್ಮ", category: "2A", nigama: "Vishwakarma" },
  { name: "Aachaari - ಆಚಾರಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Akkasaali - ಅಕ್ಕಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Ausaali - ಔಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiger - ಬಡಿಗರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiwadda - ಬಡಿವಾಡ್ಡ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Akkasali - ಬೈಲು ಅಕ್ಕಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Kammaara - ಬೈಲು ಕಮ್ಮಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bogara - ಬೋಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Chappegar - ಚಪ್ಪೇಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Chaarodi - ಚಾರೋಡಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Konkani Aachaara - ಕೊಂಕಣಿ ಆಚಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Dyvagnya Bhramana - ದೈವಜ್ಞಾಬ್ರಾಹ್ಮಣ", category: "2A", nigama: "Vishwakarma" },
  { name: "Gejjegara - ಗೆಜ್ಜೆಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kambar - ಕಂಬಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammalan - ಕಮ್ಮಾಲನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammaara - ಕಮ್ಮಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansala - ಕಂಸಾಳ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansan - ಕಂಸನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchagarh - ಕಂಚಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchora - ಕಂಚೋರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailpatar - ಬೈಲ್‌ಪತರ್‌", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchori - ಕಂಚೋರಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchugaara - ಕಂಚುಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansara - ಕಂಸಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Lohar - ಲೋಹಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Mesta - ಮೆಸ್ತ", category: "2A", nigama: "Vishwakarma" },
  { name: "Panchal - ಪಂಚಾಲ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Pathar - ಪತ್ತರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Sohgar - ಸೋಹಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Silchi - సిల్చి", category: "2A", nigama: "Vishwakarma" },
  { name: "Kasar - ಕಸಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Sonar - ಸೋನಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Soni - ಸೋನಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Sutar - ಸುತಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Tasehan - ತಸೆಹಾನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "VishwaBrahman - ವಿಶ್ವಬ್ರಾಹ್ಮಣ", category: "2A", nigama: "Vishwakarma" },
  { name: "Thattan - ಥಟ್ಟನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Aksali - ಅಕ್ಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kamsali - ಕಂಸಾಲ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Badagi - ಬಡಗಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Vokkaliga - ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Vakkaliga - ವಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Sarpa Vakkaliga - ಸರ್ಪ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Hallikar Vokkaliga - ಹಳ್ಳಿಕಾರ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Namdhari Vokkaliga - ನಾಮಧಾರಿ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gangad Kar Vokkaliga - ಗಂಗಡ್ ಕಾರ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Das Vokkaliga - ದಾಸ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Reddy Vokkaliga - ರೆಡ್ಡಿ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Marasu Vokkaliga - ಮರಸು ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gowda - ಗೌಡ", category: "3A", nigama: "Vokkaliga" },
  { name: "Hallikar - ಹಳ್ಳಿಕಾರ್", category: "3A", nigama: "Vokkaliga" },
  { name: "Kunchitiga - ಕುಂಚಿಟಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Kaup - ಕಾಪು", category: "3A", nigama: "Vokkaliga" },
  { name: "Heggade - ಹೆಗ್ಗಡೆ", category: "3A", nigama: "Vokkaliga" },
  { name: "Kamma 2 - ಕಮ್ಮ 2", category: "3A", nigama: "Vokkaliga" },
  { name: "Ruddy - ರಡ್ಡಿ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gounder - ಗೌಂಡರ್", category: "3A", nigama: "Vokkaliga" },
  { name: "Namadhari Gowda - ನಾಮಧಾರಿ ಗೌಡ", category: "3A", nigama: "Vokkaliga" },
  { name: "Uppina Kolaga/ Uttama Kolaga - ಉಪ್ಪಿನ ಕೊಳಗ/ಉತ್ತಮ ಕೊಳಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Veerashaiva Lingayat - ವೀರಶೈವ ಲಿಂಗಾಯತ", category: "Veerashaiva Lingayata (3B)", nigama: "Lingayath" },
  { name: "Panchamasali Lingayat - ಪಂಚಮಸಾಲಿ ಲಿಂಗಾಯತ", category: "3B", nigama: "Lingayath" },
  { name: "Maratha/Marata - ಮರಾತ/ಮರಾಠ", category: "Maratha", nigama: "Maratha" },
  { name: "Are-Kshatriya/Are-Maratha/Aramarata - ಅರೆ ಕ್ಷತ್ರಿ/ಅರೆ ಮರಾಠ/ಅರಮರಾಠ", category: "Maratha", nigama: "Maratha" },
  { name: "Arya/Aryaru - ಆರ್ಯ/ಆರ್ಯರು", category: "Maratha", nigama: "Maratha" },
  { name: "Konkana Maratha - ಕೊಂಕಣ ಮರಾಠ", category: "Maratha", nigama: "Maratha" },
  { name: "Kshatriya Maratha - ಕ್ಷತ್ರಿಯ ಮರಾಠ", category: "Maratha", nigama: "Maratha" },
  { name: "Kulwadi - ಕುಳವಾಡಿ", category: "Maratha", nigama: "Maratha" },
] as const;

export const CASTE_NAMES = CASTES.map((c) => c.name);

export const CASTE_CATEGORIES = Array.from(new Set(CASTES.map((c) => c.category))).filter((cat) => cat !== "nan" && cat !== "NaN");

export const NIGAMAS = Array.from(new Set(CASTES.map((c) => c.nigama))).filter((nig) => nig !== "nan" && nig !== "NaN");
